// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockNewsNotifier.Data;

#nullable disable

namespace StockNewsNotifier.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.CrawlState", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveErrors")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCrawlUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastErrorUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequestsPerSecond")
                        .HasColumnType("REAL");

                    b.Property<string>("RobotsTxt")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RobotsTxtFetchedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SourceId");

                    b.HasIndex("LastCrawlUtc");

                    b.ToTable("CrawlStates");
                });

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.NewsItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SimHash64")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WatchItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalUrl")
                        .IsUnique()
                        .HasDatabaseName("IX_NewsItem_CanonicalUrl");

                    b.HasIndex("SourceId");

                    b.HasIndex("TitleHash");

                    b.HasIndex("WatchItemId", "FetchedUtc")
                        .HasDatabaseName("IX_NewsItem_WatchItemId_FetchedUtc");

                    b.HasIndex("WatchItemId", "IsRead", "FetchedUtc");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.WatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AlertsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("Exchange", "Ticker")
                        .IsUnique()
                        .HasDatabaseName("IX_WatchItem_Exchange_Ticker");

                    b.ToTable("WatchItems");
                });

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.WatchItemSource", b =>
                {
                    b.Property<Guid>("WatchItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomQuery")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("WatchItemId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("WatchItemSources");
                });

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.CrawlState", b =>
                {
                    b.HasOne("StockNewsNotifier.Data.Entities.Source", "Source")
                        .WithOne("CrawlState")
                        .HasForeignKey("StockNewsNotifier.Data.Entities.CrawlState", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.NewsItem", b =>
                {
                    b.HasOne("StockNewsNotifier.Data.Entities.Source", "Source")
                        .WithMany("NewsItems")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockNewsNotifier.Data.Entities.WatchItem", "WatchItem")
                        .WithMany("NewsItems")
                        .HasForeignKey("WatchItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("WatchItem");
                });

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.WatchItemSource", b =>
                {
                    b.HasOne("StockNewsNotifier.Data.Entities.Source", "Source")
                        .WithMany("WatchItemSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockNewsNotifier.Data.Entities.WatchItem", "WatchItem")
                        .WithMany("WatchItemSources")
                        .HasForeignKey("WatchItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("WatchItem");
                });

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.Source", b =>
                {
                    b.Navigation("CrawlState");

                    b.Navigation("NewsItems");

                    b.Navigation("WatchItemSources");
                });

            modelBuilder.Entity("StockNewsNotifier.Data.Entities.WatchItem", b =>
                {
                    b.Navigation("NewsItems");

                    b.Navigation("WatchItemSources");
                });
#pragma warning restore 612, 618
        }
    }
}
